---
# These are required for daemonizing
:pidfile: /foo/bar
:logfile: /foo/bar/firewalls.log


:syslog:
  :address: 0.0.0.0
  :port: 50514

  # see device_maps below
  :device_maps:
    - fwsm
    - asa

:devices:
  # Login information for a device
  :fwsm:
    :host: 192.168.1.4
    :user: admin
    :pass: admin

  :asa:
    :host: 192.168.2.4
    :user: admin
    :pass: admin

:user_maps:
  :fw_admins:
    Bob: Bob Barker <bob@foo.bar>
    john: John <john@foo.bar>
    :default_suffix: fw.foo.bar

:config_managers:
  :fwsm:
    :repo:
      :path: /path/to/repo
      :push: origin master
    :tags:
      - CR\-[0-9]+
    :user_map: :fw_admins 

  :asa:
    :repo:
      :path: /path/to/repo
      :push: origin master
    :tags:
      - CR\-[0-9]+
    :user_map: :fw_admins 

# Multiple devices may be logging to the same instance of the backup program.
# Device maps map syslog messages to devices by matching the IP addresses.
:device_maps:

  # logs from 192.168.1.4-5 will be mapped to the device named "fwsm"
  :fwsm:
    - 192.168.1.4
    - 192.168.1.5
  :asa:
    - 192.168.2.4
    - 192.168.2.5

# vim: ts=2 sw=2 expandtab
